INSERT INTO weapons (weapon_id, weapon_name, base_damage, sub_stat, sub_stat_perc, weapon_effect) VALUES
    (1, 'Dull Blade', 23, Null, Null, Null),
    (2, 'Silver Sword', 33, Null, Null, Null),
    (3, 'Cool Steel', 39, 'ATK%', 7.7, 'Increases DMG against opponents affected by Hydro or Cryo by 12%.'),
    (4, 'Dark Iron Sword', 39, 'Elemental Mastery', 31, 'Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, ATK is increased by 20% for 12s.'),
    (5, 'Fillet Blade', 39, 'ATK%', 7.7, 'On hit, has a 50% chance to deal 240% ATK DMG to a single opponent. Can only occur once every 15s.'),
    (6, 'Harbinger of Dawn', 39, 'CRIT DMG%', 10.2, 'When HP is above 90%, increases CRIT Rate by 14%.'),
    (7, 'Skyrider Sword', 38, 'Energy Recharge%', 11.3, 'Using an Elemental Burst grants a 12% increase in ATK and Movement SPD for 15s.'),
    (8, 'Traveler s Handy Sword', 40, 'DEF%', 6.4, 'Each Elemental Orb or Particle collected restores 1% HP.'),
    (9, 'Blackcliff Longsword', 44, 'CRIT DMG%', 8, 'After defeating an opponent, ATK is increased by 12% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.'),
    (10, 'Favonius Sword', 41, 'Energy Recharge%', 13.3, 'CRIT Hits have a 60% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12s.'),
    (11, 'Iron Sting', 42, 'Elemental Mastery', 36, 'Dealing Elemental DMG increases all DMG by 6% for 6s. Max 2 stacks. Can occur once every 1s.'),
    (12, 'Lion s Roar', 42, 'ATK%', 9, 'Increases DMG against opponents affected by Pyro or Electro by 20%.'),
    (13, 'Prototype Rancour', 44, 'Phys DMG%', 7.5, 'On hit, Normal or Charged Attacks increase ATK and DEF by 4% for 6s. Max 4 stacks. This effect can only occur once every 0.3s.'),
    (14, 'Royal Longsword', 42, 'ATK%', 9, 'Upon damaging an opponent, increases CRIT Rate by 8%. Max 5 stacks. A CRIT Hit removes all stacks.'),
    (15, 'Sacrificial Sword', 41, 'Energy Recharge%', 13.3, 'After damaging an opponent with an Elemental Skill, the skill has a 40% chance to end its own CD. Can only occur once every 30s.'),
    (16, 'The Black Sword', 42, 'CRIT Rate%', 6, 'Increases DMG dealt by Normal and Charged Attacks by 20%. Additionally, regenerates 60% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.'),
    (17, 'The Flute', 42, 'ATK%', 9, 'Normal or Charged Attacks grant a Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100% ATK DMG to surrounding opponents. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.'),
    (18, 'Sword of Descension', 39, 'ATK%', 7.7, 'Hitting opponents with Normal and Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.'),
    (19, 'Festering Desire', 42, 'Energy Recharge%', 10, 'Increases Elemental Skill DMG by 16% and Elemental Skill CRIT Rate by 6%.'),
    (20, 'Aquila Favonia', 48, 'Phys DMG%', 9, 'ATK is increased by 20%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of resistance aloft, regenerating HP equal to 100% of ATK and dealing 200% of ATK as DMG to surrounding opponents. This effect can only occur once every 15s.'),
    (21, 'Skyward Blade', 46, 'Energy Recharge%',12, 'CRIT Rate increased by 4%. Gains Skypiercing Might upon using an Elemental Burst: Increases Movement SPD by 10%, increases ATK SPD by 10%, and Normal and Charged hits deal additional DMG equal to 20% of ATK. Skypiercing Might lasts for 12s.'),
    (22, 'Summit Shaper', 46, 'ATK%', 10.8, 'Increases Shield Strength by 20%. Scoring hits on opponents increases ATK by 4% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.'),
    (23, 'Primordial Jade Cutter', 44, 'CRIT Rate%', 9.6, 'HP increased by 20%. Additionally, provides an ATK Bonus based on 1.2% of the wielder s Max HP.');

INSERT INTO weapons (weapon_id, weapon_name, base_damage, sub_stat, sub_stat_perc, weapon_effect) VALUES
    (24, 'Waster Greatsword', 23, Null, Null, Null),
    (25, 'Old Merc s Pal', 33, Null, Null, Null),
    (26, 'Bloodtainted Greatsword', 39, 'ATK%', 7.7, 'Increases DMG against opponents affected by Hydro or Cryo by 12%.'),
    (27, 'Debate Club', 39, 'Elemental Mastery', 31, 'Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, ATK is increased by 20% for 12s.'),
    (28, 'Ferrous Shadow', 39, 'ATK%', 7.7, 'On hit, has a 50% chance to deal 240% ATK DMG to a single opponent. Can only occur once every 15s.'),
    (29, 'Skyrider Greatsword', 39, 'CRIT DMG%', 10.2, 'When HP is above 90%, increases CRIT Rate by 14%.'),
    (30, 'White Iron Greatsword', 38, 'Energy Recharge%', 11.3, 'Using an Elemental Burst grants a 12% increase in ATK and Movement SPD for 15s.'),
    (31, 'Blackcliff Slasher', 40, 'DEF%', 6.4, 'Each Elemental Orb or Particle collected restores 1% HP.'),
    (32, 'Favonius Greatsword', 44, 'CRIT DMG%', 8, 'After defeating an opponent, ATK is increased by 12% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.'),
    (33, 'Lithic Blade', 41, 'Energy Recharge%', 13.3, 'CRIT Hits have a 60% chance to generate a small amount of Elemental Particles, which will regenerate 6 Energy for the character. Can only occur once every 12s.'),
    (34, 'Prototype Archaic', 42, 'Elemental Mastery', 36, 'Dealing Elemental DMG increases all DMG by 6% for 6s. Max 2 stacks. Can occur once every 1s.'),
    (35, 'Rainslasher', 42, 'ATK%', 9, 'Increases DMG against opponents affected by Pyro or Electro by 20%.'),
    (36, 'Royal Greatsword', 44, 'Phys DMG%', 7.5, 'On hit, Normal or Charged Attacks increase ATK and DEF by 4% for 6s. Max 4 stacks. This effect can only occur once every 0.3s.'),
    (37, 'Serpent Spine', 42, 'ATK%', 9, 'Upon damaging an opponent, increases CRIT Rate by 8%. Max 5 stacks. A CRIT Hit removes all stacks.'),
    (38, 'The Bell', 41, 'Energy Recharge%', 13.3, 'After damaging an opponent with an Elemental Skill, the skill has a 40% chance to end its own CD. Can only occur once every 30s.'),
    (39, 'Whiteblind', 42, 'CRIT Rate%', 6, 'Increases DMG dealt by Normal and Charged Attacks by 20%. Additionally, regenerates 60% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.'),
    (40, 'Sacrificial Greatsword', 42, 'ATK%', 9, 'Normal or Charged Attacks grant a Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100% ATK DMG to surrounding opponents. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.'),
    (41, 'Snow-Tombed Starsilver', 39, 'ATK%', 7.7, 'Hitting opponents with Normal and Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.'),
    (42, 'Skyward Pride', 42, 'Energy Recharge%', 10, 'Increases Elemental Skill DMG by 16% and Elemental Skill CRIT Rate by 6%.'),
    (43, 'Wolf s Gravestone', 48, 'Phys DMG%', 9, 'ATK is increased by 20%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of resistance aloft, regenerating HP equal to 100% of ATK and dealing 200% of ATK as DMG to surrounding opponents. This effect can only occur once every 15s.'),
    (44, 'The Unforged', 46, 'Energy Recharge%',12, 'CRIT Rate increased by 4%. Gains Skypiercing Might upon using an Elemental Burst: Increases Movement SPD by 10%, increases ATK SPD by 10%, and Normal and Charged hits deal additional DMG equal to 20% of ATK. Skypiercing Might lasts for 12s.');